apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
images:
  - name: yourdockerhub/ai-task-backend
    newTag: 29aafc193cf9870c96d63088bb002e05bf7258f7
  - name: yourdockerhub/ai-task-frontend
    newTag: 29aafc193cf9870c96d63088bb002e05bf7258f7
  - name: yourdockerhub/ai-task-worker
    newTag: 29aafc193cf9870c96d63088bb002e05bf7258f7
patches:
  - target:
      kind: Deployment
      name: worker
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
